name: Continuous Deployment
on:
  push:
    branches: [master]
env:
  IMAGE: docker.pkg.github.com/weters/teamhex-vue/teamhex-vue
jobs:
  ci:
    name: 'Continuous Deployment'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Tags
      run: git fetch --tags

    - name: Set Version
      run: echo "::set-env name=VERSION::$(git describe --always)"

    - name: Docker Log In
      run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Docker Build
      run: |
        docker build \
          --build-arg version=$VERSION \
          -t $IMAGE:$VERSION \
          .
        docker tag $IMAGE:$VERSION $IMAGE:latest

    - name: Docker Push
      run: |
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest

    - name: Kubernetes Deploy
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: set image deploy teamhex-vue teamhex-vue=${{ env.IMAGE }}:${{ env.VERSION }} --record

    - name: Kubernetes Rollout Status
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout status deploy teamhex-vue
